version: "3.9"

services:
  api:
    # Build the development image using the Dockerfile at project root
    build:
      context: .
      dockerfile: Dockerfile
    image: go-api-dev
    # Mount the current directory for live code changes
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    # Load environment variables (e.g. META_ACCESS_TOKEN, DB_HOST, etc.)
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge